# Sales Analysis
This notebook provides a comprehensive sales analysis using the dataset `dataset_supermarket_sales.csv`.

In [1]:
# Import necessary libraries
import pandas as pd

In [7]:

# Load the dataset
df = pd.read_csv('sales.csv')
df.head()  # Display the first few rows of the dataset

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,cogs,Date,Time,Payment,Rating
0,101-17-6199,R,Trichy,Normal,Male,Food and beverages,45.79,7,16.0265,336.5565,320.53,3/13/2019,19:44,Credit card,7.0
1,101-81-4070,C,Chennai,Member,Female,Health and beauty,62.82,2,6.2820,131.9220,125.64,1/17/2019,12:36,Ewallet,4.9
2,102-06-2002,C,Chennai,Member,Male,Sports and travel,25.25,5,6.3125,132.5625,126.25,3/20/2019,17:52,Cash,6.1
3,102-77-2261,C,Chennai,Member,Male,Health and beauty,65.31,7,22.8585,480.0285,457.17,3/5/2019,18:02,Credit card,4.2
4,105-10-6182,A,Trichy,Member,Male,Fashion accessories,21.48,2,2.1480,45.1080,42.96,2/27/2019,12:22,Ewallet,6.6

In [ ]:

# 'yyyy-mm-dd'
# df['Date'] = pd.to_datetime(df['Date'])
# df['Date'] = pd.to_datetime(df['Date'], format='%m/%d/%Y')

# # # Convert 'Date' to datetime format
df['Date'] = pd.to_datetime(df['Date'], format='mixed', dayfirst=True)
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,cogs,Date,Time,Payment,Rating
0,101-17-6199,R,Trichy,Normal,Male,Food and beverages,45.79,7,16.0265,336.5565,320.53,2019-03-13,19:44,Credit card,7.0
1,101-81-4070,C,Chennai,Member,Female,Health and beauty,62.82,2,6.2820,131.9220,125.64,2019-01-17,12:36,Ewallet,4.9
2,102-06-2002,C,Chennai,Member,Male,Sports and travel,25.25,5,6.3125,132.5625,126.25,2019-03-20,17:52,Cash,6.1
3,102-77-2261,C,Chennai,Member,Male,Health and beauty,65.31,7,22.8585,480.0285,457.17,2019-05-03,18:02,Credit card,4.2
4,105-10-6182,A,Trichy,Member,Male,Fashion accessories,21.48,2,2.1480,45.1080,42.96,2019-02-27,12:22,Ewallet,6.6

In [13]:

# # # Extract hour from 'Time'
df['Hour'] = df['Time'].apply(lambda x: int(x.split(':')[0]))
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,cogs,Date,Time,Payment,Rating,Hour
0,101-17-6199,R,Trichy,Normal,Male,Food and beverages,45.79,7,16.0265,336.5565,320.53,2019-03-13,19:44,Credit card,7.0,19
1,101-81-4070,C,Chennai,Member,Female,Health and beauty,62.82,2,6.2820,131.9220,125.64,2019-01-17,12:36,Ewallet,4.9,12
2,102-06-2002,C,Chennai,Member,Male,Sports and travel,25.25,5,6.3125,132.5625,126.25,2019-03-20,17:52,Cash,6.1,17
3,102-77-2261,C,Chennai,Member,Male,Health and beauty,65.31,7,22.8585,480.0285,457.17,2019-05-03,18:02,Credit card,4.2,18
4,105-10-6182,A,Trichy,Member,Male,Fashion accessories,21.48,2,2.1480,45.1080,42.96,2019-02-27,12:22,Ewallet,6.6,12

## 1. Descriptive Statistics

In [14]:
# Total Sales
total_sales = df['Total'].sum()
print(total_sales)

664024.1055

In [15]:
# Average Sales
average_sales = df['Total'].mean()

print(average_sales)

313.2189176886792

In [16]:
df.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'cogs',
       'Date', 'Time', 'Payment', 'Rating', 'Hour'],
      dtype='str')

### Sales by Branch

In [17]:
# Sales by Branch
sales_by_branch = df.groupby('Branch')['Total'].sum()
print(sales_by_branch)

Branch
A    232055.9955
B    212672.9010
C    218958.6525
R       336.5565
Name: Total, dtype: float64

In [18]:
sales_by_branch_gender = df.groupby(['Product line', 'Gender'])['Total'].sum()
print(sales_by_branch_gender)

Product line            Gender
Electronic accessories  Female    49481.7540
                        Male      51967.4190
Fashion accessories     Female    70231.2135
                        Male      68975.6340
Food and beverages      Female    72084.1380
                        Male      52346.9520
Health and beauty       Female    43249.7520
                        Male      54478.6830
Home and lifestyle      Female    60034.2960
                        Male      45345.0060
Sports and travel       Female    49676.1300
                        Male      46153.1280
Name: Total, dtype: float64

In [19]:
sales_by_branch_gender = df.groupby(['Branch', 'Gender'])['Total'].agg(['sum', 'mean', 'count'])

print(sales_by_branch_gender)

                       sum        mean  count
Branch Gender
A      Female  107052.2145  299.866147    357
       Male    125003.7810  321.346481    389
B      Female  115445.8620  318.911221    362
       Male     97227.0390  282.636741    344
C      Female  122259.2070  340.554894    359
       Male     96699.4455  313.959239    308
R      Male       336.5565  336.556500      1

In [20]:
df.groupby('Branch').agg({
    'Total': ['sum', 'mean'],
    'Quantity': 'sum',
    'Rating': 'mean',
    'Invoice ID': 'nunique'
})

              Total             Quantity    Rating Invoice ID
                sum        mean      sum      mean    nunique
Branch
A       232055.9955  311.067018     4028  7.039946        746
B       212672.9010  301.236404     3828  6.798725        706
C       218958.6525  328.273842     3741  7.024138        667
R          336.5565  336.556500        7  7.000000          1

### Sales by City

In [22]:
# Sales by City
sales_by_city = df.groupby('City')['Total'].count()
sales_by_city

City
Chennai    667
Trichy     747
karur      706
Name: Total, dtype: int64

### Sales by Customer Type

In [23]:
# Sales by Customer Type
sales_by_customer_type = df.groupby('Customer type')['Total'].sum()
sales_by_customer_type

Customer type
Member    302776.1310
Normal    361247.9745
Name: Total, dtype: float64

### Sales by Gender

In [24]:
# Sales by Gender
sales_by_gender = df.groupby('Gender')['Total'].sum()
sales_by_gender

Gender
Female    344757.2835
Male      319266.8220
Name: Total, dtype: float64

### Sales by Product Line

In [25]:
# Sales by Product Line
sales_by_product_line = df.groupby('Product line')['Total'].sum()
sales_by_product_line

Product line
Electronic accessories    101449.1730
Fashion accessories       139206.8475
Food and beverages        124431.0900
Health and beauty          97728.4350
Home and lifestyle        105379.3020
Sports and travel          95829.2580
Name: Total, dtype: float64

### Sales by Payment Method

In [26]:
# Sales by Payment Method
sales_by_payment = df.groupby('Payment')['Total'].sum()
sales_by_payment

Payment
Cash           225935.9235
Credit card    196917.7350
Ewallet        241170.4470
Name: Total, dtype: float64

### Average Rating by Product Line

In [27]:
# Average Rating by Product Line
average_rating_by_product_line = df.groupby('Product line')['Rating'].mean()
average_rating_by_product_line

Product line
Electronic accessories    6.876147
Fashion accessories       6.868243
Food and beverages        7.148068
Health and beauty         6.916779
Home and lifestyle        6.971471
Sports and travel         6.920395
Name: Rating, dtype: float64

In [28]:
df.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'cogs',
       'Date', 'Time', 'Payment', 'Rating', 'Hour'],
      dtype='str')

## 2. Time Series Analysis

### Monthly Sales Trend

In [31]:
# Monthly Sales Trend
monthly_sales_trend = df.resample('MS', on='Date')['Total'].sum()
print(monthly_sales_trend)

Date
2019-01-01    141233.4315
2019-02-01    106106.8050
2019-03-01    124772.8860
2019-04-01     28433.2020
2019-05-01     23272.5255
2019-06-01     28791.1575
2019-07-01     30944.0775
2019-08-01     30960.6255
2019-09-01     37650.7530
2019-10-01     30339.6555
2019-11-01     26901.3255
2019-12-01     25202.2890
2020-01-01      3145.6845
2020-02-01      1896.4785
2020-03-01      2076.6060
2020-04-01         0.0000
2020-05-01       675.8430
2020-06-01      1015.9905
2020-07-01         0.0000
2020-08-01      2486.5050
2020-09-01       478.2330
2020-10-01       711.8475
2020-11-01       810.6000
2020-12-01         0.0000
2021-01-01      5346.6735
2021-02-01      4972.2015
2021-03-01      1443.2460
2021-04-01         0.0000
2021-05-01      1423.1280
2021-06-01       367.7835
2021-07-01       827.4945
2021-08-01         0.0000
2021-09-01         0.0000
2021-10-01      1084.7970
2021-11-01       652.2600
Freq: MS, Name: Total, dtype: float64

### Daily Sales Trend

In [32]:
# Daily Sales Trend
daily_sales_trend = df.resample('D', on='Date')['Total'].sum()
daily_sales_trend

Date
2019-01-01    7107.7440
2019-01-02    4390.9215
2019-01-03    4922.2530
2019-01-04       0.0000
2019-01-05       0.0000
                ...
2021-10-29       0.0000
2021-10-30       0.0000
2021-10-31       0.0000
2021-11-01       0.0000
2021-11-02     652.2600
Freq: D, Name: Total, Length: 1037, dtype: float64

### Sales by Hour of the Day

In [33]:
# Sales by Hour
sales_by_hour = df.groupby('Hour')['Total'].sum()
sales_by_hour

Hour
8      1644.6780
9      7936.0260
10    67165.3500
11    66834.4425
12    54216.5295
13    66196.9140
14    54282.6585
15    67995.4905
16    54967.1115
17    47276.2710
18    61584.5895
19    68130.2580
20    45793.7865
Name: Total, dtype: float64

## 3. Customer Analysis

### Sales by Customer Type

In [34]:
# Sales by Customer Type
sales_by_customer_type = df.groupby('Customer type')['Total'].sum()
sales_by_customer_type

Customer type
Member    302776.1310
Normal    361247.9745
Name: Total, dtype: float64

### Sales by Gender

In [35]:
# Sales by Gender
sales_by_gender = df.groupby('Gender')['Total'].sum()
sales_by_gender

Gender
Female    344757.2835
Male      319266.8220
Name: Total, dtype: float64

### Average Purchase per Customer

In [36]:
# Average Purchase per Customer
average_purchase_per_customer = df['Total'].mean()
average_purchase_per_customer

np.float64(313.2189176886792)

## 4. Product Analysis

### Sales by Product Line

In [37]:
# Sales by Product Line
sales_by_product_line = df.groupby('Product line')['Total'].sum()
sales_by_product_line

Product line
Electronic accessories    101449.1730
Fashion accessories       139206.8475
Food and beverages        124431.0900
Health and beauty          97728.4350
Home and lifestyle        105379.3020
Sports and travel          95829.2580
Name: Total, dtype: float64

### Most and Least Popular Products

In [38]:
# Most Popular Products
most_popular_products = df.groupby('Product line')['Quantity'].sum().sort_values(ascending=False)
most_popular_products

Product line
Fashion accessories       2475
Food and beverages        2235
Electronic accessories    1807
Home and lifestyle        1770
Health and beauty         1661
Sports and travel         1656
Name: Quantity, dtype: int64

In [39]:
# Least Popular Products
least_popular_products = df.groupby('Product line')['Quantity'].sum().sort_values(ascending=True)
least_popular_products

Product line
Sports and travel         1656
Health and beauty         1661
Home and lifestyle        1770
Electronic accessories    1807
Food and beverages        2235
Fashion accessories       2475
Name: Quantity, dtype: int64

### Revenue Contribution by Product Line

In [40]:
# Revenue Contribution
revenue_contribution = df.groupby('Product line')['Total'].sum() / total_sales * 100
revenue_contribution

Product line
Electronic accessories    15.277935
Fashion accessories       20.964126
Food and beverages        18.738942
Health and beauty         14.717604
Home and lifestyle        15.869801
Sports and travel         14.431593
Name: Total, dtype: float64

## 5. Payment Analysis

### Sales by Payment Method

In [41]:
# Sales by Payment Method
sales_by_payment_method = df.groupby('Payment')['Total'].sum()
sales_by_payment_method

Payment
Cash           225935.9235
Credit card    196917.7350
Ewallet        241170.4470
Name: Total, dtype: float64

## 6. Rating Analysis

### Average Rating by Product Line

In [42]:
# Average Rating by Product Line
average_rating_by_product_line = df.groupby('Product line')['Rating'].mean()
average_rating_by_product_line

Product line
Electronic accessories    6.876147
Fashion accessories       6.868243
Food and beverages        7.148068
Health and beauty         6.916779
Home and lifestyle        6.971471
Sports and travel         6.920395
Name: Rating, dtype: float64

### Rating Distribution

In [43]:
# Rating Distribution
rating_distribution = df['Rating'].value_counts()
rating_distribution

Rating
4.2     64
6.2     64
7.5     56
8.0     55
5.1     52
        ..
4.7     25
5.3     24
6.8     24
4.6     21
10.0    15
Name: count, Length: 61, dtype: int64

In [44]:
rating_distribution = df['Rating'].round().value_counts().sort_index()
print(rating_distribution)

Rating
4.0     225
5.0     285
6.0     413
7.0     297
8.0     412
9.0     306
10.0    182
Name: count, dtype: int64

## 7. Branch Analysis

### Branch Performance

In [39]:
# Branch Performance
branch_performance = df.groupby('Branch').agg({'Total': ['sum', 'mean', 'count']})
branch_performance

              Total
                sum        mean count
Branch
A       106200.3705  312.354031   340
B       106197.6720  319.872506   332
C       110568.7065  337.099715   328

## 8. Profit Analysis

### Gross Profit and Profit Margin

In [40]:
# Gross Profit
df['Gross Profit'] = df['Total'] - df['cogs']
# Profit Margin
df['Profit Margin'] = (df['Gross Profit'] / df['Total']) * 100
gross_profit = df['Gross Profit'].sum()
profit_margin = df['Profit Margin'].mean()
gross_profit, profit_margin

(15379.368999999999, 4.761904761904762)